version: '3.8'

services:
  postgres-estoque:
    image: postgres:15
    container_name: postgres-estoque
    environment:
      POSTGRES_DB: estoquedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - estoque_pgdata:/var/lib/postgresql/data

volumes:
  estoque_pgdata:
