spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/pedidodb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    feign: DEBUG
    feign.Logger: DEBUG
    br.com.fiap.Pedido.interfaces.gateways: DEBUG

server:
  port: 8083

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
