version: '3.8'

services:
  postgres-cliente:
    image: postgres:15
    container_name: postgres-cliente
    environment:
      POSTGRES_DB: clientedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - cliente_pgdata:/var/lib/postgresql/data

volumes:
  cliente_pgdata:
